<a href="https://colab.research.google.com/github/Nadiatulkhoir/ali/blob/main/Aljabar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]])
B = np.array ([[1,4,6],[4,2,8],[6,2,4]])
C = np.array ([[2,3],[4,6],[4,2]])
D = np.array ([[2,4,5],[3,6,8],[5,4,9]])
C.shape[0]

3

In [ ]:
A =np.random.randint(10,size=(3,3))
print(A)

[[3 4 5]
 [9 8 1]
 [8 6 7]]


In [ ]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]])
B = np.array ([[1,4,6],[4,2,8],[6,2,4]])
c = 2
d = 4
e = c +d
F = e*A
G = c*A
H = d*A
I = (c*A) + (d*A)
print(I)

[[ 6 12 24]
 [12 18 36]
 [18  6 30]]


In [ ]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]])
B = np.array ([[1,4,6],[4,2,8],[6,2,4]])
F = (A * B)
print(F)

[[ 1  8 24]
 [ 8  6 48]
 [18  2 20]]


In [ ]:
C = np.array ([[2,3],[4,6],[4,2]])

C_T = C.transpose()
print(C)
print('\n')
print(C_T)

[[2 3]
 [4 6]
 [4 2]]


[[2 4 4]
 [3 6 2]]


In [ ]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]])
B = np.array ([[1,4,6],[4,2,8],[6,2,4]])
D = np.array ([[2,4,5],[3,6,8],[5,4,9]])

A_T = A.transpose()
B_T = B.transpose()
D_T = D.transpose()
D = (A_T + B_T) * D_T
print(D)



[[  4  18  45]
 [ 24  30  12]
 [ 50 112  81]]


In [1]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]])
B = np.array ([[1,4,6],[4,2,8],[6,2,4]])
C = np.array ([[2,3],[4,6],[4,2]])
D = np.array ([[2,4,5],[3,6,8],[5,4,9]])

def aljabar(matrix):
  matrix=[]
  for i in matrix:
    if A

print("matrix 1:")
print(matrix1)


matrix 1:
[[33 16 38]
 [50 26 60]
 [37 24 46]]
