# Tugas 3

In [1]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]])
B = np.array ([[1,4,6],[4,2,8],[6,2,4]])
C = np.array ([[2,3],[4,6],[4,2]])
D = np.array ([[2,4,5],[3,6,8],[5,4,9]])

print(A)
print(C)

[[1 2 4]
 [2 3 6]
 [3 1 5]]
[[2 3]
 [4 6]
 [4 2]]


In [2]:
#cara cepat untuk mengalikan matrix dengan nilai random
A =np.random.randint(10,size=(3,3))
print(A)

[[4 3 6]
 [4 3 9]
 [7 7 3]]


Operasi-operasi Matrik


1) Matriks dalam bentuk apapun dapat dikalikan dengan skalar c, d.

In [3]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]])
B = np.array ([[1,4,6],[4,2,8],[6,2,4]])
c = 2
d = 4
e = c + d
G = (c+d)*A
H = (c*A) + (d*A)
print('e =', e)
print('G =', G)
print('H =', H)

e = 6
G = [[ 6 12 24]
 [12 18 36]
 [18  6 30]]
H = [[ 6 12 24]
 [12 18 36]
 [18  6 30]]


2. Matriks yang ukurannya sama bisa dijumlahkan. 

Hasilnya adalah semua elemen yang bersesuaian dan ditambah dalam bentuk.

In [4]:
K = A + B
#L = A + C
print('K =', K)
#print('L =', L)

K = [[ 2  6 10]
 [ 6  5 14]
 [ 9  3  9]]


3. Jika banyaknya kolom dari matrix A adalah sama dengan banyaknya baris matrik B, maka kedua matrik dapat dikalikan dalam bentuk perkalian A,B. Dengan jumlah baris yang mengikuti matriks A dan kolom mengikuti matriks B.

In [ ]:
#Cara menentukan ukuran matriks:
#  namamatriks.shape
print(C.shape)

#Cara menentukan jumlah baris:
#  namamatriks.shape[0]
print(C.shape[0])

#Cara menentukan jumlah kolom:
#  namamatriks.shape[1]
print(C.shape[1])

In [7]:
(2, 3)
2
3

3

In [8]:
print(A*B)

[[ 1  8 24]
 [ 8  6 48]
 [18  2 20]]


In [9]:
print(A@B)

[[33 16 38]
 [50 26 60]
 [37 24 46]]


Matriks Tranpose

(Baris jadi kolom, dan sebaliknya) Transpose matriks A……

note : Matriks Covarian adalah matriks awal dikali matriks transposenya.

In [11]:
A = np.array ([[1,2,4],[2,3,6],[3,1,5]])

A_T = A.transpose()
print(A)
print('\n')
print(A_T)

[[1 2 4]
 [2 3 6]
 [3 1 5]]


[[1 2 3]
 [2 3 1]
 [4 6 5]]


In [15]:
C = np.array ([[2,3],[4,6],[4,2]])

C_T = C.transpose()
print(C)
print('\n')
print(C_T)

[[2 3]
 [4 6]
 [4 2]]


[[2 4 4]
 [3 6 2]]


In [16]:
import numpy as np

A = np.array([[1, 2, 4], [2, 3, 6], [3, 1, 5]])
B = np.array([[1, 4, 6], [4, 2, 8], [6, 2, 4]])
C = np.array([[2, 3], [4, 6], [4, 2]])
D = np.array([[2, 4, 5], [3, 6, 8], [5, 4, 9]])

# Perkalian elemen demi elemen dari matriks A, B, dan D
t = A * B * D
print(t)
print(" ")

# Transpose dari matriks t
tt = t.transpose()
print(tt)
print(" ")
print(" ")

# Perkalian elemen demi elemen dari transpose matriks A, B, dan D
a = A.transpose()
b = B.transpose()
dd = D.transpose()
print(a * b * dd)
print(" ")
print(" ")

# (A+B)*D
abd = np.dot((A + B), D)
ABD = abd.transpose()
print(ABD)
print(" ")
print(" ")

# (A+B)*C
abc = np.dot((A + B), C)
ABC = abc.transpose()
print(ABC)


[[  2  32 120]
 [ 24  36 384]
 [ 90   8 180]]
 
[[  2  24  90]
 [ 32  36   8]
 [120 384 180]]
 
 
[[  2  24  90]
 [ 32  36   8]
 [120 384 180]]
 
 
[[ 72  97  72]
 [ 84 110  90]
 [148 196 150]]
 
 
[[68 88 66]
 [62 76 63]]


Matriks Elementer

R_3 - 7*R_1

Mengalikan Matriks

In [19]:
import numpy as np

A = np.array([[1, 2, 4], [2, 3, 6], [3, 1, 5]])
B = np.array([[1, 4, 6], [4, 2, 8], [6, 2, 4]])
C = np.array([[2, 3], [4, 6], [4, 2]])
D = np.array([[2, 4, 5], [3, 6, 8], [5, 4, 9]])

# Mengalikan matriks A dengan matriks B
AB = np.dot(A, B)

# Mengalikan matriks AB dengan matriks C
ABC = np.dot(AB, C)

# Mengalikan matriks A dengan matriks D
AD = np.dot(A, D)

# Mengalikan matriks AB dengan matriks D
ABD = np.dot(AB, D)

# Mengalikan matriks A dengan matriks B, lalu hasilnya dikalikan dengan matriks D
ABD_alt = np.dot(A, np.dot(B, D))

# Menampilkan hasil
print("Hasil perkalian matriks A dengan matriks B:")
print(AB)
print("\nHasil perkalian matriks A dengan matriks B, lalu dikalikan dengan matriks C:")
print(ABC)
print("\nHasil perkalian matriks A dengan matriks D:")
print(AD)
print("\nHasil perkalian matriks A dan B, lalu hasilnya dikalikan dengan matriks D:")
print(ABD)
print("\nHasil alternatif perkalian matriks A dengan matriks B, lalu dikalikan dengan matriks D:")
print(ABD_alt)


Hasil perkalian matriks A dengan matriks B:
[[33 16 38]
 [50 26 60]
 [37 24 46]]

Hasil perkalian matriks A dengan matriks B, lalu dikalikan dengan matriks C:
[[282 271]
 [444 426]
 [354 347]]

Hasil perkalian matriks A dengan matriks D:
[[28 32 57]
 [43 50 88]
 [34 38 68]]

Hasil perkalian matriks A dan B, lalu hasilnya dikalikan dengan matriks D:
[[304 380 635]
 [478 596 998]
 [376 476 791]]

Hasil alternatif perkalian matriks A dengan matriks B, lalu dikalikan dengan matriks D:
[[304 380 635]
 [478 596 998]
 [376 476 791]]
